name: Publish NuGet Package

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: '1'
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 9.0.x

      - name: Install Versionize
        run: dotnet tool install --global Versionize

      - name: Configure Git
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"

      - name: Run Versionize
        run: versionize
        continue-on-error: true

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore --configuration Release

      - name: Test
        run: dotnet test --no-build --configuration Release

      - name: Pack
        run: dotnet pack --no-build --configuration Release --output ./nupkg

      - name: Push to NuGet
        run: dotnet nuget push "./nupkg/*.nupkg" --api-key ${{secrets.NUGET_KEY}} --source https://api.nuget.org/v3/index.json --skip-duplicate

      - name: Run Versionize and capture version
        id: versionize
        run: |

          VERSION=$(sed -n 's/.*<Version>\(.*\)<\/Version>.*/\1/p' src/Squid.Prism.Engine.Core/Squid.Prism.Engine.Core.csproj)
          if [ ! -z "$VERSION" ]; then
            echo "New version: $VERSION"
            echo "version=$VERSION" >> $GITHUB_OUTPUT
            git tag "v$VERSION"
            git push origin "v$VERSION"
            echo "changelog<<EOF" >> $GITHUB_OUTPUT
            cat CHANGELOG.md >> $GITHUB_OUTPUT
            echo "EOF" >> $GITHUB_OUTPUT
          fi
        continue-on-error: true

      - name: Create GitHub Release
        if: steps.versionize.outputs.version != ''
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ steps.versionize.outputs.version }}
          name: Release v${{ steps.versionize.outputs.version }}
          body: ${{ steps.versionize.outputs.changelog }}
          draft: false
          prerelease: false
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Checkout develop
        run: |
          git fetch
          git checkout develop
          git pull

#      - name: Merge main into develop
#        run: |
#          git merge main
#          git push origin develop
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
